language: ruby
bundler_args: --without copyright
matrix:
  include:
    - rvm: jruby
      jdk: openjdk6
      script: rm -r src/test/java; mvn test
    - rvm: jruby
      jdk: openjdk7
      script: rm -r src/test/java; mvn test
    - rvm: jruby
      jdk: oraclejdk7
      script: rm -r src/test/java; mvn test
    - rvm: jruby
      jdk: oraclejdk8
      script: rm -r src/test/java; mvn test
    - rvm: ruby
      jdk: openjdk7
      script: mvn verify -DskipTests -Dinvoker.test='*,!executable_*'
    - rvm: ruby
      jdk: oraclejdk8
      script: mvn verify -DskipTests -Dinvoker.test=executable_*
  allow_failures:
    - rvm: ruby
